version: '3.8'

services:
  app:
    image: laravel_app_new:latest
    container_name: laravel_app_prod
    ports:
      - "80:8000"
    environment:
      APP_ENV: "production"
      APP_DEBUG: "false"
      DB_CONNECTION: "mysql"
      DB_HOST: "db"                       # Correspond au nom du service MySQL
      DB_PORT: 3306
      DB_DATABASE: "laravel_db"           # Correspond à MYSQL_DATABASE
      DB_USERNAME: "laravel_user"         # Correspond à MYSQL_USER
      DB_PASSWORD: "laravel_password"     # Correspond à MYSQL_PASSWORD
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: laravel_db_prod
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root          # Mot de passe pour l'utilisateur root
      MYSQL_DATABASE: laravel_db         # Nom de la base de données
      MYSQL_USER: laravel_user           # Un utilisateur supplémentaire
      MYSQL_PASSWORD: laravel_password   # Mot de passe pour cet utilisateur
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - laravel_db_data:/var/lib/mysql
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 60s  # Augmenté pour donner plus de temps à MySQL

volumes:
  laravel_db_data:

networks:
  laravel_network:
    driver: bridge
