version: '3.8'

services:
  app:
    image: laravel_app_new:latest
    container_name: laravel_app_prod
    ports:
      - "80:8000"
    environment:
      APP_ENV: production
      APP_DEBUG: 'false'
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: laravel_db_prod
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data_prod:/var/lib/mysql
    networks:
      - laravel_network

volumes:
  db_data_prod:

networks:
  laravel_network:
    driver: bridge
